exclude: "^\
  (third-party/.*)\
  "

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict # checks for some markers such as "<<<<<<<", "=======", and ">>>>>>>".
      - id: detect-private-key # detects the presence of private keys.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: trailing-whitespace # trims trailing whitespace at the end of lines.

  # Format YAML and other files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$

  # Sort the order of importing libs
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]

  # Format Python files
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          [
            --ignore=F401,
            --max-line-length=120,
            --max-complexity=18,
            --select=B,
            C,
            E,
            F,
            W,
            T4,
            B9,
          ]
        exclude: |
          (?x)^(
            \.git
            | __pycache__
            | docs/source/conf\.py
            | old
            | build
            | dist
            | Diffusion
            | logs
            | migrations
          )/
